### ISSUE TITLE
Is it possible to split this Icon-Font?

### ISSUE THREAD

**Issue by cyberpunkbln** [ForkAwesome/Fork-Awesome#253] opened 2020-06-24 22:42 UTC
Hello,
only a short questions is it possible to split this font into theme based fonts?

Like
1. Web Application Icons
2. Brands
and so on

or give it an special site where your prpject are embeded?

thx

**Comment by cyberpunkbln** [comment] 2020-06-25 18:52
Cool,
a system like https://remixicon.com/ will be also great.

**Comment by shinenelson** [comment] 2021-07-10 12:26
Duplicate of #53

**Closed by shinenelson** 2021-07-10 12:26 UTC
Labels: enhancement
